package com.spendwise.app.presentation.screens.report

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.spendwise.app.core.apiErrorMessage
import com.spendwise.app.data.remote.api.IntelligenceApi
import com.spendwise.app.data.remote.dto.MonthlyReportDto
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import java.time.LocalDate
import javax.inject.Inject

data class MonthlyReportState(
    val selectedMonth: Int = LocalDate.now().monthValue,
    val selectedYear: Int  = LocalDate.now().year,
    val report: MonthlyReportDto? = null,
    val isLoading: Boolean = false,
    val error: String? = null
)

@HiltViewModel
class MonthlyReportViewModel @Inject constructor(
    private val intelligenceApi: IntelligenceApi
) : ViewModel() {
    private val _state = MutableStateFlow(MonthlyReportState())
    val state: StateFlow<MonthlyReportState> = _state

    init { load() }

    fun load() {
        viewModelScope.launch {
            val month = _state.value.selectedMonth
            val year  = _state.value.selectedYear
            _state.value = _state.value.copy(isLoading = true, error = null)
            try {
                val resp = intelligenceApi.getMonthlyReport(month, year)
                if (resp.isSuccessful && resp.body()?.success == true) {
                    _state.value = _state.value.copy(report = resp.body()!!.data, isLoading = false)
                } else {
                    _state.value = _state.value.copy(isLoading = false, error = resp.apiErrorMessage())
                }
            } catch (e: Exception) {
                _state.value = _state.value.copy(isLoading = false, error = e.message ?: "Network error")
            }
        }
    }

    fun selectMonth(month: Int, year: Int) {
        _state.value = _state.value.copy(selectedMonth = month, selectedYear = year)
        load()
    }

    /** Build a shareable plain-text summary of the report */
    fun buildShareText(): String {
        val r = _state.value.report ?: return "No report data"
        val monthName = java.time.Month.of(r.month).getDisplayName(java.time.format.TextStyle.FULL, java.util.Locale.getDefault())
        val sb = StringBuilder()
        sb.appendLine("📊 SpendWise Monthly Report — $monthName ${r.year}")
        sb.appendLine("═".repeat(40))
        sb.appendLine()
        sb.appendLine("💰 SUMMARY")
        sb.appendLine("  Income:       ₹${"%,.0f".format(r.summary.income)}")
        sb.appendLine("  Total Spent:  ₹${"%,.0f".format(r.summary.totalSpent)}")
        sb.appendLine("  Savings:      ₹${"%,.0f".format(r.summary.savings)}")
        sb.appendLine("  Savings Rate: ${r.summary.savingsRate}%")
        sb.appendLine("  vs Last Month: ${if (r.summary.vsLastMonth >= 0) "+" else ""}${r.summary.vsLastMonth}%")
        sb.appendLine()
        sb.appendLine("🏆 HEALTH SCORE: ${r.healthScore.score}/100 (${r.healthScore.grade})")
        sb.appendLine()
        sb.appendLine("📂 CATEGORY BREAKDOWN")
        r.categoryBreakdown.take(8).forEach { cat ->
            val emoji = categoryEmoji(cat.categorySlug)
            sb.appendLine("  $emoji ${cat.categorySlug.replaceFirstChar { it.uppercase() }}: ₹${"%,.0f".format(cat.amount)} (${cat.pctOfTotal}%)")
        }
        sb.appendLine()
        if (r.topMerchants.isNotEmpty()) {
            sb.appendLine("🏪 TOP MERCHANTS")
            r.topMerchants.take(5).forEach { m ->
                sb.appendLine("  ${m.merchant}: ₹${"%,.0f".format(m.totalSpent)} (${m.visitCount} visits)")
            }
            sb.appendLine()
        }
        if (r.insights.isNotEmpty()) {
            sb.appendLine("💡 INSIGHTS")
            r.insights.take(3).forEach { ins -> sb.appendLine("  • ${ins.message}") }
            sb.appendLine()
        }
        sb.appendLine("Generated by SpendWise")
        return sb.toString()
    }
}

fun categoryEmoji(slug: String): String = when (slug.lowercase()) {
    "food", "groceries"  -> "🍽️"
    "transport"          -> "🚗"
    "shopping"           -> "🛍️"
    "entertainment"      -> "🎬"
    "utilities"          -> "💡"
    "health"             -> "🏥"
    "education"          -> "📚"
    "travel"             -> "✈️"
    "rent", "housing"    -> "🏠"
    "emi", "loan"        -> "🏦"
    "investment"         -> "📈"
    "salary"             -> "💰"
    else                 -> "💳"
}
